
deathlog_settings = {
	["colored_tooltips"] = false,
	["minilog"] = {
		["title_color_a"] = 1,
		["entry_font_size"] = 14,
		["title_color_b"] = 0,
		["title_color_g"] = 0.8196079134941101,
		["lock"] = false,
		["show_icon"] = false,
		["pos_x"] = 376.6666705322277,
		["title_font_size"] = 19,
		["size_x"] = 491.6666870117188,
		["entry_x_offset"] = 0,
		["font"] = "default_font",
		["title_x_offset"] = 0,
		["pos_y"] = 169.8668909072876,
		["border_alpha"] = 1,
		["title_color_r"] = 1,
		["enable"] = true,
		["tooltip_class"] = true,
		["max_lvl"] = 60,
		["tooltip_race"] = true,
		["tooltip_name"] = true,
		["hide_subtitle_heading"] = false,
		["theme"] = "None",
		["entry_y_offset"] = 0,
		["columns"] = {
			"Name", -- [1]
			"Class", -- [2]
			"Race", -- [3]
			"Lvl", -- [4]
			"Zone", -- [5]
			"LastWords", -- [6]
		},
		["tooltip_lastwords"] = true,
		["min_lvl"] = 1,
		["entry_font"] = "default_font",
		["show_title"] = true,
		["presets"] = "Yazpad",
		["tooltip_zone"] = true,
		["tooltip_date"] = true,
		["tooltip_killedby"] = true,
		["size_y"] = 171.6666564941406,
		["title_y_offset"] = 0,
		["tooltip_guild"] = true,
		["tooltip_loc"] = true,
	},
	["Heatmap WorldMap Overlay"] = {
		["enable"] = true,
		["show_checkbox_on_map"] = true,
	},
	["Corpse Tooltip"] = {
		["enable_ctt"] = true,
	},
	["DeathAlert"] = {
		["font_color_r"] = 1,
		["min_lvl"] = 1,
		["display_time"] = 6,
		["enable"] = true,
		["fire_message"] = "<name> the <race> <class> has died from fire.\n at lvl <level> in <zone>.",
		["pos_y"] = 250,
		["accent_color_g"] = 1,
		["font_color_b"] = 1,
		["max_lvl"] = 60,
		["alert_sound"] = "default_hardcore",
		["min_lvl_player"] = false,
		["drown_message"] = "<name> the <race> <class> drowned\n at lvl <level> in <zone>.",
		["fatigue_message"] = "<name> the <race> <class> has died from fatigue.\n at lvl <level> in <zone>.",
		["lava_message"] = "<name> the <race> <class> drowned in lava.\n at lvl <level> in <zone>.",
		["pos_x"] = 0,
		["guild_only"] = false,
		["font"] = "Nimrod MT",
		["size_x"] = 600,
		["accent_color_r"] = 1,
		["accent_color_b"] = 1,
		["size_y"] = 200,
		["current_zone_filter"] = false,
		["message"] = "<name> the <race> <class> has been slain\nby <source> at lvl <level> in <zone>.",
		["font_size"] = 16,
		["slime_message"] = "<name> the <race> <class> has died from slime.\n at lvl <level> in <zone>.",
		["style"] = "boss_banner_enemy_icon_medium",
		["accent_color_a"] = 1,
		["font_color_a"] = 1,
		["fall_message"] = "<name> the <race> <class> fell to\ndeath at lvl <level> in <zone>.",
		["font_color_g"] = 1,
		["alert_subset"] = "faction_wide",
	},
	["Heatmap Indicator"] = {
		["size_x"] = 40,
		["pos_y"] = 0,
		["enable"] = false,
		["size_y"] = 40,
		["show_value"] = false,
		["pos_x"] = 0,
	},
	["deathless_logging"] = true,
	["show_minimap"] = true,
}
deathlog_data = {
	["Stitches"] = {
		["Mygirl-27314"] = {
			["class_id"] = 1,
			["guild"] = "",
			["date"] = 1695795444,
			["map_pos"] = "0.4370,0.1376",
			["source_id"] = 6519,
			["name"] = "Mygirl",
			["last_words"] = "",
			["level"] = 51,
			["map_id"] = 1449,
			["race_id"] = 1,
		},
		["Palafanta-52667"] = {
			["class_id"] = 2,
			["guild"] = "Cave Raiders",
			["date"] = 1695795578,
			["map_pos"] = "0.4875,0.3074",
			["source_id"] = -1,
			["name"] = "Palafanta",
			["level"] = 40,
			["race_id"] = 1,
			["map_id"] = 1434,
		},
		["Ворошилов-48871"] = {
			["class_id"] = 3,
			["guild"] = "",
			["date"] = 1695794590,
			["map_pos"] = "0.3667,0.3757",
			["source_id"] = -1,
			["name"] = "Ворошилов",
			["level"] = 1,
			["race_id"] = 4,
			["map_id"] = 1437,
		},
		["Chardoneigh-41731"] = {
			["class_id"] = 5,
			["guild"] = "One Life Cats",
			["date"] = 1695794700,
			["map_pos"] = "0.5586,0.1664",
			["source_id"] = 2405,
			["name"] = "Chardoneigh",
			["last_words"] = "just need that damn punch card :P:",
			["level"] = 32,
			["map_id"] = 1424,
			["race_id"] = 4,
		},
		["Terpenkek-18241"] = {
			["class_id"] = 4,
			["guild"] = "",
			["date"] = 1695794340,
			["map_pos"] = "0.4502,0.7339",
			["source_id"] = -1,
			["name"] = "Terpenkek",
			["level"] = 6,
			["map_id"] = 1415,
			["race_id"] = 1,
		},
		["Ssx-20230"] = {
			["class_id"] = 4,
			["guild"] = "",
			["date"] = 1695793419,
			["map_pos"] = "0.4211,0.7246",
			["source_id"] = -1,
			["name"] = "Ssx",
			["level"] = 44,
			["map_id"] = 1414,
			["race_id"] = 1,
		},
		["Evelknievel-18502"] = {
			["class_id"] = 9,
			["guild"] = "",
			["date"] = 1695793491,
			["map_pos"] = "0.4489,0.7605",
			["source_id"] = -1,
			["name"] = "Evelknievel",
			["last_words"] = "",
			["level"] = 27,
			["map_id"] = 1415,
			["race_id"] = 7,
		},
		["Wxx-47218"] = {
			["class_id"] = 9,
			["guild"] = "Sulfuron Breeding Center",
			["date"] = 1695795442,
			["map_pos"] = "0.3981,0.4698",
			["source_id"] = 1135,
			["name"] = "Wxx",
			["last_words"] = "",
			["level"] = 7,
			["map_id"] = 1426,
			["race_id"] = 7,
		},
		["Synrogue-64870"] = {
			["class_id"] = 4,
			["guild"] = "",
			["date"] = 1695795644,
			["map_pos"] = "0.6824,0.5423",
			["source_id"] = 7234,
			["name"] = "Synrogue",
			["map_id"] = 1438,
			["level"] = 6,
			["race_id"] = 4,
		},
		["Slackmode-45467"] = {
			["class_id"] = 11,
			["guild"] = "Hemliga Klubben",
			["date"] = 1695795636,
			["map_pos"] = "0.6468,0.2181",
			["source_id"] = 12922,
			["name"] = "Slackmode",
			["last_words"] = "snowTBC? har jag xd",
			["map_id"] = 1435,
			["level"] = 40,
			["race_id"] = 4,
		},
		["Hagrit-11767"] = {
			["class_id"] = 3,
			["guild"] = "",
			["date"] = 1695793711,
			["map_pos"] = "0.2833,0.4259",
			["source_id"] = -1,
			["name"] = "Hagrit",
			["level"] = 8,
			["map_id"] = 1426,
			["race_id"] = 3,
		},
		["Vasculin-40223"] = {
			["class_id"] = 9,
			["guild"] = "",
			["date"] = 1695795063,
			["map_pos"] = "0.5501,0.6843",
			["source_id"] = 735,
			["name"] = "Vasculin",
			["level"] = 7,
			["race_id"] = 7,
			["map_id"] = 1429,
		},
		["Btalr-36651"] = {
			["class_id"] = 4,
			["guild"] = "",
			["date"] = 1695795114,
			["map_pos"] = "0.5234,0.2307",
			["source_id"] = 2233,
			["name"] = "Btalr",
			["last_words"] = "",
			["level"] = 18,
			["map_id"] = 1439,
			["race_id"] = 1,
		},
		["Wakou-57547"] = {
			["class_id"] = 5,
			["guild"] = "",
			["date"] = 1695794576,
			["map_pos"] = "0.4631,0.3657",
			["source_id"] = -1,
			["name"] = "Wakou",
			["race_id"] = 3,
			["level"] = 31,
			["map_id"] = 1415,
			["last_words"] = "",
		},
		["Rognex-26551"] = {
			["class_id"] = 1,
			["guild"] = "",
			["date"] = 1695795645,
			["map_pos"] = "0.7703,0.4688",
			["source_id"] = 3757,
			["name"] = "Rognex",
			["last_words"] = "",
			["map_id"] = 1440,
			["level"] = 29,
			["race_id"] = 1,
		},
		["Blowing-9231"] = {
			["class_id"] = 3,
			["guild"] = "",
			["date"] = 1695795128,
			["map_pos"] = "0.7072,0.6700",
			["source_id"] = 1167,
			["name"] = "Blowing",
			["last_words"] = "",
			["level"] = 19,
			["map_id"] = 1432,
			["race_id"] = 4,
		},
		["Happytime-59532"] = {
			["class_id"] = 2,
			["guild"] = "",
			["date"] = 1695795275,
			["map_pos"] = "0.5294,0.6394",
			["source_id"] = 285,
			["name"] = "Happytime",
			["race_id"] = 1,
			["level"] = 8,
			["map_id"] = 1429,
			["last_words"] = "",
		},
		["Verystronk-8318"] = {
			["class_id"] = 1,
			["guild"] = "",
			["date"] = 1695795013,
			["map_pos"] = "0.2139,0.4092",
			["source_id"] = 3742,
			["name"] = "Verystronk",
			["last_words"] = "",
			["level"] = 20,
			["map_id"] = 1440,
			["race_id"] = 1,
		},
	},
}
deathlog_data_map = {
	["Stitches"] = {
		["Ворошилов"] = "Ворошилов-48871",
		["Blowing"] = "Blowing-9231",
		["Vasculin"] = "Vasculin-40223",
		["Chardoneigh"] = "Chardoneigh-41731",
		["Terpenkek"] = "Terpenkek-18241",
		["Wakou"] = "Wakou-57547",
		["Mygirl"] = "Mygirl-27314",
		["Verystronk"] = "Verystronk-8318",
		["Happytime"] = "Happytime-59532",
		["Slackmode"] = "Slackmode-45467",
		["Ssx"] = "Ssx-20230",
		["Wxx"] = "Wxx-47218",
		["Rognex"] = "Rognex-26551",
		["Synrogue"] = "Synrogue-64870",
		["Evelknievel"] = "Evelknievel-18502",
		["Hagrit"] = "Hagrit-11767",
		["Palafanta"] = "Palafanta-52667",
		["Btalr"] = "Btalr-36651",
	},
}
dev_precomputed_general_stats = nil
dev_precomputed_log_normal_params = nil
dev_precomputed_skull_locs = nil
dev_class_data = nil
